name = "MyQuantum"
uuid = "6053dad5-5ea9-4561-ad32-9b14f501a2c6"
authors = ["Anand Jain"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
